CREATE TABLE IF NOT EXISTS pipeline_watermark (
    pipeline_name VARCHAR(96) PRIMARY KEY,
    `last_value` BIGINT NOT NULL DEFAULT 0,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
