[pytest]
testpaths = tests
pythonpath = pyspark
filterwarnings =
    ignore:`torch\.jit\.trace` is deprecated:FutureWarning
    ignore:`torch\.jit\.trace_method` is deprecated:FutureWarning
    ignore:You are using the legacy TorchScript-based ONNX export.*:DeprecationWarning
    ignore:The feature will be removed\. Please remove usage of this function:DeprecationWarning
